apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: myapp           # MUST MATCH deployment labels
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080