name: CI - Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t app:ci .
        

  push-image:
    name: Build & push to GHCR
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # allow pushing to GitHub Container Registry
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/app:latest
            ghcr.io/${{ github.repository_owner }}/app:${{ github.sha }}

      - name: Show pushed image
        run: echo "Pushed ghcr.io/${{ github.repository_owner }}/app:latest"
        
              