name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the official Hadolint Action (no Docker daemon needed)
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        # If you want warnings to NOT fail CI at first:
        continue-on-error: true

      - name: Set up QEMU (cross-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Local build to catch Dockerfile errors early
      - name: Build image (local test)
        run: docker build -t app:ci .

  push-image:
    name: Scan then Push to GHCR (multi-arch)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build to local docker daemon so Trivy can scan it
      - name: Build image for scan (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: app:ci-scan

      # Trivy scan (report-only for now so it won't fail CI)
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: app:ci-scan
          format: table
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
        continue-on-error: true

      # Build & push multi-arch image
      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/bidishanits/app:latest
            ghcr.io/bidishanits/app:${{ github.sha }}
